Create Program.cs
VladimirPolozov/Delegates pull request #1
Opened 2024-03-19 08:04 UTC by VladimirPolozov

2024-03-23 18:43 UTC, iredb requested changes

2024-03-23 18:43 UTC, iredb commented on Program.cs
> +    public void AutoFill(int extension, int minElement = -10, int MaxElement = 10)
![image](https://github.com/VladimirPolozov/Delegates/assets/120615742/1bb179f6-fe28-4322-a47c-e9ce23155bf7)

2024-03-23 18:43 UTC, iredb commented on Program.cs
> +        return matrix.MatrixArray[0, 0];
действительно можно убрать фигурные скобки, если блок if содержит всего одну инструкцию, но это не отменяет того, что у содержимого блока добавляется таб. в строке перед return должно быть два таба, а не 1 таб и 2 пробела.
а вообще Леонид Николаевич против такой конструкции, так что лучше не злить папу и просто поставить фигурные скобки.

2024-03-23 18:43 UTC, iredb commented on Program.cs
> +          continue;
содержимое блока должно быть с отступом в 1 табуляцию.

2024-03-23 18:43 UTC, iredb commented on Program.cs
> +    public void DiagonalizeMatrix(SquareMatrix matrix, DiagonalizeMatrixDelegate diagonalizeMethod)
почему бы не избавиться от части "Matrix" имени метода? в твоем случае получится matrix.DiagonalizeMatrix, нечто вроде тавтологии.
можно сделать matrix.Diagonalize,
или еще лучше matrix.Diagonalized, потому что первый случай выглядит как изменение содержимого объекта, к которому мы обращаемся (matrix).
по аналогии с питоновскими list.sort() (сортирует list) и sorted(list) (не меняет list, возвращает содержимое list в отсортированном виде

2024-03-23 18:43 UTC, iredb commented on Program.cs
> +    };
![image](https://github.com/VladimirPolozov/Delegates/assets/120615742/14b9d528-f823-4472-a033-ba8e2fcab553)

2024-03-23 18:43 UTC, iredb commented on Program.cs
> +      // Ожидание нажатия клавиши (чтобы окно не закрывалось сразу после выполнения программы)
кажется, текст в console.writeline строкой выше должен избавлять тебя от необходимости писать такой комментарий

2024-03-24 05:25 UTC, iredb commented on Program.cs
> +          continue;
только под конце заметил, что везде такие отступы. сделай таб = 4 пробела.

2024-03-24 09:05 UTC, VladimirPolozov commented on Program.cs
> +    };
Здесь анонимный делегат объявляется

2024-03-24 09:05 UTC, VladimirPolozov commented on Program.cs
> +      // Ожидание нажатия клавиши (чтобы окно не закрывалось сразу после выполнения программы)
Ок

2024-03-24 09:38 UTC, VladimirPolozov commented on Program.cs
> +    public void AutoFill(int extension, int minElement = -10, int MaxElement = 10)
Что должно быть изменено? Все параметры и локальные переменные в camelCase

2024-03-24 09:42 UTC, VladimirPolozov commented on Program.cs
> +        return matrix.MatrixArray[0, 0];
Исправлено

2024-03-24 09:46 UTC, VladimirPolozov commented on Program.cs
> +    public void DiagonalizeMatrix(SquareMatrix matrix, DiagonalizeMatrixDelegate diagonalizeMethod)
Исправил

2024-03-24 09:49 UTC, VladimirPolozov commented on Program.cs
> +    public void AutoFill(int extension, int minElement = -10, int MaxElement = 10)
Исправлено

2024-03-24 11:05 UTC, iredb approved these changes

2024-03-24 14:30 UTC, merged

2024-03-25 03:30 UTC, VladimirPolozov commented on Program.cs
> +          continue;
Исправлено